### ISSUE TITLE
Replace text with data?

### ISSUE THREAD

**Issue by marijnbent** [meetrais/LLM-Fine-Tuning#1]
So is text where you put your training data? What format do you use for it?

**Comment by meetrais** [comment]
I imported data for training like below in "finetune_mistral_7b.py" file. But that data worsened my output response, so I commented that code. You can check which dataset is relevant to your use-case and train your fine-tuned model.

from datasets import load_dataset
dataset_name = "gathnex/Gath_baize"
dataset = load_dataset(dataset_name, split="train[:1000]")

Alternatively, if you want to  train your model with limited domain specific data then I suggest you have a look at Retrieval Augmented Generation(RAG). I have example code for RAG in my [LlamaLlama](https://github.com/meetrais/LlamaLlama) repository.
